# Generated by Django 5.2 on 2025-09-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentacion", "0002_artefacto_contexto"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="eventos_esperados",
            field=models.TextField(
                blank=True, null=True, verbose_name="Eventos y Resultados Esperados"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="funcionalidades_clave",
            field=models.TextField(
                blank=True, null=True, verbose_name="Funcionalidades Clave"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="necesidades_usuarios",
            field=models.TextField(
                blank=True, null=True, verbose_name="Necesidades de Usuarios"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="objetivo_principal",
            field=models.TextField(
                blank=True, null=True, verbose_name="Objetivo Principal"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="procesos_principales",
            field=models.TextField(
                blank=True, null=True, verbose_name="Procesos Principales"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reglas_restricciones",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reglas y Restricciones"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="usuarios_finales",
            field=models.TextField(
                blank=True, null=True, verbose_name="Usuarios Finales"
            ),
        ),
    ]
