# Generated by Django 5.2 on 2025-09-30 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentacion", "0003_project_eventos_esperados_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="eventos_esperados",
        ),
        migrations.RemoveField(
            model_name="project",
            name="funcionalidades_clave",
        ),
        migrations.RemoveField(
            model_name="project",
            name="necesidades_usuarios",
        ),
        migrations.RemoveField(
            model_name="project",
            name="procesos_principales",
        ),
        migrations.RemoveField(
            model_name="project",
            name="usuarios_finales",
        ),
        migrations.CreateModel(
            name="UsuarioFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="documentacion.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario Final",
                "verbose_name_plural": "Usuarios Finales",
                "unique_together": {("proyecto", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="ProcesoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procesos",
                        to="documentacion.usuariofinal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proceso de Usuario",
                "verbose_name_plural": "Procesos de Usuarios",
            },
        ),
        migrations.CreateModel(
            name="NecesidadUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="necesidades",
                        to="documentacion.usuariofinal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Necesidad de Usuario",
                "verbose_name_plural": "Necesidades de Usuarios",
            },
        ),
    ]
