# Generated by Django 5.2 on 2025-09-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentacion", "0004_remove_project_eventos_esperados_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="reglas_restricciones",
        ),
    ]
