# Generated by Django 5.2 on 2025-11-10 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentacion", "0005_remove_project_reglas_restricciones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procesousuario",
            name="usuario",
        ),
        migrations.AlterUniqueTogether(
            name="usuariofinal",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usuariofinal",
            name="proyecto",
        ),
        migrations.RemoveField(
            model_name="project",
            name="objetivo_principal",
        ),
        migrations.CreateModel(
            name="SecurityQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pregunta1",
                    models.CharField(
                        choices=[
                            ("color", "¿Cuál es tu color favorito?"),
                            ("comida", "¿Cuál es tu comida favorita?"),
                            ("pelicula", "¿Cuál es tu película favorita?"),
                            ("libro", "¿Cuál es tu libro favorito?"),
                            ("deporte", "¿Cuál es tu deporte favorito?"),
                            ("musica", "¿Cuál es tu género de música favorito?"),
                        ],
                        max_length=50,
                    ),
                ),
                ("respuesta1", models.CharField(max_length=128)),
                (
                    "pregunta2",
                    models.CharField(
                        choices=[
                            ("color", "¿Cuál es tu color favorito?"),
                            ("comida", "¿Cuál es tu comida favorita?"),
                            ("pelicula", "¿Cuál es tu película favorita?"),
                            ("libro", "¿Cuál es tu libro favorito?"),
                            ("deporte", "¿Cuál es tu deporte favorito?"),
                            ("musica", "¿Cuál es tu género de música favorito?"),
                        ],
                        max_length=50,
                    ),
                ),
                ("respuesta2", models.CharField(max_length=128)),
                (
                    "pregunta3",
                    models.CharField(
                        choices=[
                            ("color", "¿Cuál es tu color favorito?"),
                            ("comida", "¿Cuál es tu comida favorita?"),
                            ("pelicula", "¿Cuál es tu película favorita?"),
                            ("libro", "¿Cuál es tu libro favorito?"),
                            ("deporte", "¿Cuál es tu deporte favorito?"),
                            ("musica", "¿Cuál es tu género de música favorito?"),
                        ],
                        max_length=50,
                    ),
                ),
                ("respuesta3", models.CharField(max_length=128)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta de Seguridad",
                "verbose_name_plural": "Preguntas de Seguridad",
            },
        ),
        migrations.DeleteModel(
            name="NecesidadUsuario",
        ),
        migrations.DeleteModel(
            name="ProcesoUsuario",
        ),
        migrations.DeleteModel(
            name="UsuarioFinal",
        ),
    ]
