# Generated by Django 5.2 on 2025-11-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0006_remove_procesousuario_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefacto',
            name='requisitos_relacionados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de RF implementados en este artefacto'),
        ),
    ]
