# Generated by Django 5.2 on 2025-11-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0007_artefacto_requisitos_relacionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefacto',
            name='historia_usuario_relacionada',
            field=models.CharField(blank=True, help_text='Nombre de la HU a la que pertenece este diagrama', max_length=255, null=True),
        ),
    ]
