# Generated by Django 5.2 on 2025-11-13 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0008_artefacto_historia_usuario_relacionada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebacajaNegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito_id', models.CharField(help_text='Ej: RF1, RF2, etc.', max_length=50)),
                ('numero_prueba', models.IntegerField(help_text='Número secuencial de la prueba')),
                ('descripcion_requisito', models.TextField(help_text='Descripción del RF')),
                ('historia_usuario_relacionada', models.CharField(blank=True, help_text='HU a la que pertenece el RF', max_length=255, null=True)),
                ('objetivo_prueba', models.TextField()),
                ('datos_entrada', models.TextField()),
                ('procedimiento', models.TextField()),
                ('resultado_esperado', models.TextField()),
                ('resultado_obtenido', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_EJECUCION', 'En Ejecución'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20)),
                ('resultado_final', models.CharField(choices=[('APTO', 'Apto'), ('NO_APTO', 'No Apto'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('generado_por_ia', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_caja_negra', to='documentacion.project')),
            ],
            options={
                'verbose_name': 'Prueba de Caja Negra',
                'verbose_name_plural': 'Pruebas de Caja Negra',
                'ordering': ['numero_prueba'],
                'unique_together': {('proyecto', 'requisito_id', 'numero_prueba')},
            },
        ),
    ]
