# Generated by Django 5.2 on 2025-11-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0009_pruebacajanegra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebacajanegra',
            name='requisitos_relacionados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de RFs que cubre esta prueba'),
        ),
    ]
