# Generated by Django 5.2 on 2025-11-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0010_pruebacajanegra_requisitos_relacionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='necesidades_usuarios',
            field=models.TextField(blank=True, help_text='Necesidades específicas de los usuarios del proyecto', null=True),
        ),
    ]
