# Generated by Django 5.2 on 2025-11-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0011_project_necesidades_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='usuarios_finales',
            field=models.TextField(blank=True, help_text='Usuarios finales del proyecto (en formato JSON)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='necesidades_usuarios',
            field=models.TextField(blank=True, help_text='Necesidades específicas de los usuarios del proyecto (en formato JSON)', null=True),
        ),
    ]
