# Generated by Django 5.2 on 2025-11-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0012_project_usuarios_finales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='necesidades_usuarios',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usuarios_finales',
        ),
        migrations.AddField(
            model_name='project',
            name='usuarios_necesidades',
            field=models.TextField(blank=True, help_text='Usuarios finales y sus necesidades específicas', null=True),
        ),
    ]
