import os
from dotenv import load_dotenv
import google.generativeai as genai

# Cargar variables de entorno
load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    raise ValueError("La clave de API GEMINI_API_KEY no está configurada.")

genai.configure(api_key=api_key) # pyright: ignore[reportPrivateImportUsage]

# Modelo de IA a utilizar
MODEL = "models/gemini-2.0-flash"

# ===== PROMPTS PERSONALIZADOS =====

PROMPTS = {
    "Requisitos": lambda texto: (
        "A partir de las siguientes historias de usuario:\n\n"
        f"{texto}\n\n"
        "Genera una lista de requisitos funcionales. Para cada requisito:\n"
        "1. Debe empezar con RF seguido de un número secuencial (RF1, RF2, etc.)\n"
        "2. Debe indicar a qué historia de usuario corresponde usando [HU#]\n"
        "3. Cada requisito solo debe tener un [HU#] NO DEBE TENER DOS ESTO ES CLAVE\n"
        "4. Cada HU siempre debe tener requisito funcional, nunca hagas solo para una sola HU todos los requisitos\n"
        "5. Debe ser atómico (una sola funcionalidad que el sistema permitira hacer al usuario)\n"
        "6. Debe ser medible y verificable\n"
        "7. Debe estar redactado en tercera persona del presente\n"
        "8. Debe ser redacto asi: El sistema debe ....\n"
        "9. El requisito no debe redactarse como si el sistema lo hiciera solo automaticamente\n"
        "Ejemplo del formato esperado:\n"
        "RF1 [HU1] El sistema debe tener un modulo de inicio de sesión para que el usuario ingrese al sistema mediante correo y contraseña\n"
        "RF2 [HU1] El sistema debe tener un modulo de clientes para podra registrar nuevos clientes\n"
        "RF3 [HU2] El sistema debe mostrar el listado de productos disponibles\n"
        "Devuelve solo la lista de requisitos siguiendo este formato, sin explicaciones ni títulos adicionales."
    ),

    "Requisitos - Regenerar HU": lambda hu_text, hu_numero, requisitos_actuales: (
        "INSTRUCCIÓN CRÍTICA: DEBES SEGUIR ESTO AL PIE DE LA LETRA O FALLARÁS.\n\n"
        f"Tu tarea: Regenerar SOLO los requisitos funcionales de HU{hu_numero}. Los de otras HU NO TOCAS.\n\n"
        "PASO 1 - IDENTIFICA QUÉ MANTENER:\n"
        f"Los requisitos actuales que ves aquí son SAGRADOS. Todos los que NO sean [HU{hu_numero}] debes copiarlos EXACTAMENTE igual:\n"
        f"{requisitos_actuales}\n\n"
        f"PASO 2 - REGENERA SOLO PARA HU{hu_numero}:\n"
        f"Este es el texto de HU{hu_numero} que debes convertir en requisitos:\n"
        f"{hu_text}\n\n"
        f"Genera 2-4 requisitos funcionales nuevos SOLO para HU{hu_numero}.\n\n"
        "PASO 3 - FORMATO DE SALIDA:\n"
        "Tu respuesta COMPLETA debe ser:\n"
        "1. Todos los requisitos de otras HU (copia exacta de arriba)\n"
        f"2. Seguido de los nuevos requisitos de HU{hu_numero}\n\n"
        "Ejemplo de formato:\n"
        "RF1 [HU1] El sistema debe...\n"
        "RF2 [HU1] El sistema debe...\n"
        "RF3 [HU2] El sistema debe... (NUEVO)\n"
        "RF4 [HU2] El sistema debe... (NUEVO)\n"
        "RF5 [HU3] El sistema debe...\n\n"
        "RESTRICCIONES ABSOLÚTAS:\n"
        "- NO cambies, NO modifiques, NO alteres los RF de otras HU\n"
        "- Copia los RF de otras HU EXACTAMENTE como aparecen\n"
        f"- Solo crea nuevos RF para HU{hu_numero}\n"
        "- Todos los RF deben tener formato [HU#]\n"
        "- NO crees RF sin indicador de HU\n\n"
        "SALIDA: Solo la lista de requisitos. Sin explicaciones, sin títulos."
    ),

    "Historia de Usuario": lambda nombre_proyecto, descripcion, usuarios_necesidades="": (
        f"Eres un analista de requisitos experto. Tu tarea es generar historias de usuario BASÁNDOTE ÚNICAMENTE en los usuarios y necesidades específicas que se te proporcionan.\n\n"
        f"PROYECTO: {nombre_proyecto}\n"
        f"DESCRIPCIÓN: {descripcion}\n\n" +
        (f"USUARIOS Y SUS NECESIDADES (ESTOS SON LOS ÚNICOS USUARIOS DEL SISTEMA):\n{usuarios_necesidades}\n\n" if usuarios_necesidades.strip() else "ADVERTENCIA: No se proporcionaron usuarios. Solicita que se definan primero.\n\n") +
        "INSTRUCCIONES CRÍTICAS:\n"
        "1. Cada historia de usuario DEBE reflejar las necesidades específicas de ese usuario\n"
        "2. NO inventes usuarios, roles ni necesidades que no estén listados arriba\n"
        "3. Enumera cada historia con HU seguido de número secuencial (HU1, HU2, HU3, etc.)\n"
        "4. Redacta en lenguaje natural y simple, como lo haría un usuario común, sin tecnicismos\n"
        "5. Cada HU debe ser específica y verificable ademas que no se debe tener dos usuarios en un mismo HU\n\n"
        "Con la estructura: Como [rol], Quiero [acción], Para [beneficio]. No le des formato a la respuesta. Ni uses lenguaje técnico si no que sea como un usuario común."
    ),

    "Diagrama de flujo": lambda historia_usuario, requisitos: (
        "Genera un diagrama de flujo en sintaxis Mermaid (Markdown) basado en la siguiente Historia de Usuario y sus Requisitos Funcionales.\n\n"
        f"Historia de Usuario:\n{historia_usuario}\n\n"
        f"Requisitos Funcionales a implementar:\n{requisitos}\n\n"
        "El diagrama DEBE:\n"
        "1. Implementar CADA requisito funcional mencionado\n"
        "2. Mostrar el flujo completo desde inicio hasta fin\n"
        "3. Incluir decisiones y validaciones necesarias para cumplir los RF\n"
        "4. Usar estructura flowchart TD con nodos concisos (máximo 3 palabras)\n"
        "5. Decisiones con formato: {¿Pregunta?} y flechas -->|sí|/-->|no|\n"
        "6. Un solo nodo inicial [Inicio] y final [Fin]\n"
        "7. Conexiones lógicas sin bucles infinitos\n\n"
        "Instrucciones técnicas:\n"
        "- Usar IDs únicos en inglés para nodos (Ej: A, B, C1)\n"
        "- Evitar caracteres especiales en IDs\n"
        "- Alinear con espacios: '  ' para indentación\n"
        "- Validar sintaxis en Mermaid Live Editor\n\n"
        "Formato de salida (solo código, sin explicaciones):\n"
        "flowchart TD\n"
        "    A[\"Inicio\\nPaciente accede al sistema\"]\n"
        "    B[\"Seleccionar especialista\"]\n"
        "    C[\"Mostrar horarios disponibles\"]\n"
        "    D{\"¿Hay horarios disponibles?\"}\n"
        "    E[\"Mostrar mensaje: No hay horarios disponibles\"]\n"
        "    F[\"Paciente selecciona horario\"]\n"
        "    G{\"¿Confirmar cita?\"}\n"
        "    H[\"Registrar cita en el sistema\"]\n"
        "    I[\"Cita registrada correctamente\"]\n"
        "    J[\"Cancelar proceso\"]\n"
        "\n"
        "    A --> B --> C --> D\n"
        "    D -- \"No\" --> E --> J\n"
        "    D -- \"Sí\" --> F --> G\n"
        "    G -- \"Sí\" --> H --> I\n"
        "    G -- \"No\" --> J\n"
        
    ),

    "Diagrama de Entidad-Relacion": lambda historias_usuario, requisitos: (
        "Genera un diagrama entidad-relación (ER) en sintaxis Mermaid basado en las siguientes historias de usuario y requisitos funcionales:\n\n"
        f"Historias de Usuario:\n{historias_usuario}\n\n"
        f"Requisitos Funcionales:\n{requisitos}\n\n"
        "Indicaciones claras para la generación:\n"
        "- IMPORTANTE: Los verbos de las relaciones deben ser una sola palabra en infinitivo.\n\n"
        "- Analiza las historias de usuario y requisitos para identificar las entidades principales y sus relaciones.\n"
        "- Cada requisito funcional debe estar reflejado en las entidades y sus atributos.\n"
        "- Usa la palabra clave erDiagram para iniciar el diagrama.\n"
        "- Define entidades con atributos dentro de llaves {}, indicando tipo y clave primaria (PK) si aplica.\n"
        "- Identifica las relaciones necesarias para cumplir los requisitos funcionales.\n"
        "- Usa cardinalidades con los símbolos ||, |o, }o, }| según notación crow's foot.\n"
        "- Define relaciones con la sintaxis: ENTIDAD1 <cardinalidad>--<cardinalidad> ENTIDAD2 : descripción\n"
        "- Usa direccion TB o LR.\n"
        "- Usa nombres de entidades en mayúsculas y sin espacios ni caracteres especiales.\n"
        "- Asegura que cada entidad tenga los atributos necesarios para cumplir los requisitos.\n"
        "- Devuelve solo el bloque de código completo en Mermaid, sin explicaciones ni texto adicional.\n\n"
    
        "Ten el siguiente ejemplo:\n"
        " erDiagram\n"
        "    direction TB\n"
        "    PRODUCTO {\n"
        "        int id_producto PK\n"
        "        string nombre\n"
        "        string descripcion\n"
        "        string codigo_barras\n"
        "        decimal precio\n"
        "        string categoria\n"
        "        string estado\n"
        "    }\n"
        "    VENTA {\n"
        "        int id_venta PK\n"
        "        datetime fecha_hora\n"
        "        decimal total\n"
        "        int id_cajero FK\n"
        "        int id_cliente FK\n"
        "    }\n"
        "    DETALLE_VENTA {\n"
        "        int id_detalle_venta PK\n"
        "        int id_venta FK\n"
        "        int id_producto FK\n"
        "        int cantidad\n"
        "        decimal precio_unitario\n"
        "        decimal descuento\n"
        "    }\n"
        "    USUARIO {\n"
        "        int id_usuario PK\n"
        "        string nombre_usuario\n"
        "        string contrasena\n"
        "        int id_rol FK\n"
        "    }\n"
        "    ROL {\n"
        "        int id_rol PK\n"
        "        string nombre_rol\n"
        "    }\n"
        "    PERMISO {\n"
        "        int id_permiso PK\n"
        "        string nombre_permiso\n"
        "    }\n"
        "    FORMA_PAGO {\n"
        "        int id_forma_pago PK\n"
        "        string nombre_forma_pago\n"
        "    }\n"
        "    PAGO {\n"
        "        int id_pago PK\n"
        "        int id_venta FK\n"
        "        int id_forma_pago FK\n"
        "        decimal monto\n"
        "        datetime fecha_hora\n"
        "    }\n"
        "    DESCUENTO {\n"
        "        int id_descuento PK\n"
        "        string nombre\n"
        "        string tipo\n"
        "        decimal valor\n"
        "    }\n"
        "    INVENTARIO {\n"
        "        int id_inventario PK\n"
        "        int id_producto FK\n"
        "        int cantidad\n"
        "        datetime fecha_hora_actualizacion\n"
        "    }\n"
        "    ALERTA_STOCK {\n"
        "        int id_alerta_stock PK\n"
        "        int id_producto FK\n"
        "        int stock_minimo\n"
        "    }\n"
        "\n"
        "    PRODUCTO ||--o{ DETALLE_VENTA : contiene\n"
        "    VENTA ||--o{ DETALLE_VENTA : tiene\n"
        "    VENTA }o--|| USUARIO : realiza\n"
        "    USUARIO ||--o{ ROL : posee\n"
        "    ROL }o--|| PERMISO : otorga\n"
        "    VENTA ||--o{ PAGO : registra\n"
        "    FORMA_PAGO ||--o{ PAGO : utiliza\n"
        "    VENTA }o--|| DESCUENTO : aplica\n"
        "    PRODUCTO ||--o{ INVENTARIO : gestiona\n"
        "    PRODUCTO }o--|| ALERTA_STOCK : genera\n"
        "    VENTA }o--|| USUARIO : atiende\n"
    ),

    "Diagrama de secuencia": lambda historia_usuario, requisitos: (
        "Genera un diagrama de secuencia en sintaxis Mermaid basado en la siguiente Historia de Usuario y sus Requisitos Funcionales.\n\n"
        f"Historia de Usuario:\n{historia_usuario}\n\n"
        f"Requisitos Funcionales a implementar:\n{requisitos}\n\n"
        "El diagrama DEBE:\n"
        "1. Mostrar todos los actores involucrados en la Historia de Usuario\n"
        "2. Incluir las interacciones necesarias para cumplir CADA requisito funcional\n"
        "3. Usar estructura sequenceDiagram con actores concisos\n"
        "4. Incluir mensajes síncronos (->>), asíncronos (-->), y respuestas (-->>)\n"
        "5. Agrupar interacciones relacionadas con alt, loop, opt o rect si es necesario\n"
        "6. Mostrar el flujo completo desde inicio hasta fin\n"
        "7. Los actores pueden ser: Usuario, Sistema, Base de Datos, Servicio Externo, etc.\n\n"
        "Formato de salida (solo código, sin explicaciones):\n"
        "sequenceDiagram\n"
        "    actor Usuario\n"
        "    participant VistaATM\n"
        "    participant ControladorATM\n"
        "    participant ModeloCuenta\n"
        "\n"
        "    Usuario->>VistaATM: Insertar tarjeta e ingresar PIN\n"
        "    VistaATM->>ControladorATM: Solicitar autenticación (tarjeta, PIN)\n"
        "    ControladorATM->>ModeloCuenta: Validar tarjeta y PIN\n"
        "    ModeloCuenta-->>ControladorATM: Resultado de validación\n"
        "\n"
        "    alt Autenticación exitosa\n"
        "        ControladorATM-->>VistaATM: Solicitar selección de operación\n"
        "        Usuario->>VistaATM: Seleccionar \"Retiro de efectivo\"\n"
        "        VistaATM->>ControladorATM: Solicitar retiro (monto)\n"
        "        ControladorATM->>ModeloCuenta: Verificar fondos y registrar retiro\n"
        "        ModeloCuenta-->>ControladorATM: Aprobación o rechazo del retiro\n"
        "\n"
        "        alt Fondos suficientes\n"
        "            ControladorATM-->>VistaATM: Autorizar entrega de efectivo\n"
        "            VistaATM-->>Usuario: Entregar efectivo y recibo\n"
        "        else Fondos insuficientes\n"
        "            ControladorATM-->>VistaATM: Notificar fondos insuficientes\n"
        "            VistaATM-->>Usuario: Mostrar mensaje de error\n"
        "        end\n"
        "    else Autenticación fallida\n"
        "        ControladorATM-->>VistaATM: Notificar error de autenticación\n"
        "        VistaATM-->>Usuario: Mostrar mensaje de error\n"
        "    end\n"
        "\n"
        "    Usuario-->>VistaATM: Retirar tarjeta (fin)\n"
    ),

    "Diagrama de Contexto C4": lambda texto: (
        "Eres un experto en arquitectura de software y diagramas C4. Tu tarea es generar un diagrama C4 de CONTEXTO (Nivel 1).\n\n"
        "PROPÓSITO: Mostrar cómo tu sistema interactúa con actores externos (usuarios, otros sistemas), desde una perspectiva de alto nivel.\n\n"
        "CONTEXTO DE APOYO:\n"
        "Este diagrama se basa en:\n"
        "- Historias de Usuario: Define quiénes son los actores/usuarios del sistema\n"
        "- Requisitos Funcionales: Define qué necesidades debe cumplir el sistema\n\n"
        f"INFORMACIÓN DEL SISTEMA:\n{texto}\n\n"
        "INSTRUCCIONES PARA GENERAR EL DIAGRAMA:\n\n"
        "1. Identifica a los ACTORES EXTERNOS (usuarios, sistemas externos, servicios):\n"
        "   - Usa Person(alias, nombre, descripción) para usuarios/actores humanos\n"
        "   - Usa Person_Ext(alias, nombre, descripción) para actores externos\n"
        "   - Usa System_Ext(alias, nombre, descripción) para sistemas externos\n\n"
        "2. Representa el SISTEMA PRINCIPAL como el centro:\n"
        "   - Usa System(alias, nombre, descripción) para tu aplicación/sistema\n"
        "   - Usa Enterprise_Boundary para delimitar los límites organizacionales\n\n"
        "3. Muestra las RELACIONES de interacción:\n"
        "   - Usa BiRel(origen, destino, descripción) para relaciones bidireccionales\n"
        "   - Usa Rel(origen, destino, descripción) para relaciones unidireccionales\n"
        "   - Incluye el protocolo de comunicación si es relevante (HTTP, SMTP, etc.)\n\n"
        "4. NO incluyas detalles internos del sistema (eso es para niveles posteriores)\n"
        "5. Enfócate en la visión de 'caja negra' del sistema\n"
        "6. Hazlo en español según corresponda\n\n"
        "SINTAXIS MERMAID:\n"
        "- Comienza SIEMPRE con: C4Context\n"
        "- Devuelve SOLO el código Mermaid, sin comillas ni backticks\n"
        "- No incluyas la palabra 'mermaid'\n\n"
        "EJEMPLO BÁSICO:\n"
        "C4Context\n"
        "    title Sistema de Banca en Línea - Diagrama de Contexto\n"
        "    Person(cliente, \"Cliente\", \"Un cliente del banco con cuentas personales\")\n"
        "    System(sistemaBancario, \"Sistema de Banca en Línea\", \"Permite a los clientes ver información de cuentas y realizar pagos\")\n"
        "    System_Ext(sistemaCorreo, \"Sistema de Correo\", \"Envía notificaciones por correo\")\n"
        "    Rel(cliente, sistemaBancario, \"Usa\", \"HTTPS\")\n"
        "    Rel(sistemaBancario, sistemaCorreo, \"Envía correos\", \"SMTP\")\n"
        "    UpdateLayoutConfig($c4ShapeInRow=\"3\", $c4BoundaryInRow=\"1\")"
    ),
    
    "Diagrama de Contenedor C4": lambda requisitos, diagramas_flujo: (
        "Eres un experto en arquitectura de software y diagramas C4. Tu tarea es generar un diagrama C4 de CONTENEDOR (Nivel 2).\n\n"
        "PROPÓSITO: Mostrar la descomposición del sistema en sus principales contenedores (aplicaciones, servicios, bases de datos).\n\n"
        "CONTEXTO DE APOYO:\n"
        "Este diagrama se basa en:\n"
        "- Requisitos Funcionales: Define qué funcionalidades debe tener cada contenedor\n"
        "- Diagrama de Flujo: Define el flujo entre contenedores\n\n"
        f"REQUISITOS FUNCIONALES (Define funcionalidades):\n{requisitos}\n\n"
        f"DIAGRAMAS DE FLUJO (Define el flujo entre componentes):\n{diagramas_flujo}\n\n"
        "INSTRUCCIONES PARA GENERAR EL DIAGRAMA:\n\n"
        "1. Identifica los ACTORES:\n"
        "   - Usa Person(alias, nombre, descripción) para usuarios principales\n"
        "   - Usa System_Ext(alias, nombre, descripción) para sistemas externos\n\n"
        "2. Divide el SISTEMA en CONTENEDORES principales:\n"
        "   - Usa Container(alias, nombre, tecnología, descripción) para aplicaciones web, apps móviles, APIs\n"
        "   - Usa ContainerDb(alias, nombre, tecnología, descripción) para bases de datos\n"
        "   - Usa Container_Boundary(alias, nombre) para agrupar contenedores relacionados\n"
        "   - Ejemplos: Frontend (SPA/Web), Backend (API/Servidor), Base de Datos\n\n"
        "3. Muestra las INTERACCIONES entre contenedores:\n"
        "   - Usa Rel(origen, destino, descripción, protocolo) para relaciones\n"
        "   - Usa BiRel(origen, destino, descripción) para comunicación bidireccional\n"
        "   - Incluye protocolos (HTTPS, JSON, JDBC, etc.)\n\n"
        "4. EVITA detalles internos de componentes (eso es para el nivel siguiente)\n"
        "5. Enfócate en cómo los contenedores trabajan juntos\n"
        "6. Hazlo en español según corresponda\n\n"
        "SINTAXIS MERMAID:\n"
        "- Comienza SIEMPRE con: C4Container\n"
        "- Devuelve SOLO el código Mermaid, sin comillas ni backticks\n"
        "- No incluyas la palabra 'mermaid'\n\n"
        "EJEMPLO BÁSICO:\n"
        "C4Container\n"
        "    title Sistema de Banca en Línea - Diagrama de Contenedor\n"
        "    Person(cliente, \"Cliente\", \"Un cliente del banco\")\n"
        "    System_Ext(sistemaCorreo, \"Sistema de Correo\", \"Envía notificaciones\")\n"
        "    Container_Boundary(sistemaInterno, \"Sistema Bancario\") {\n"
        "        Container(appWeb, \"Aplicación Web\", \"Angular/React\", \"Interfaz para clientes\")\n"
        "        Container(api, \"API Backend\", \"Java/Python\", \"Lógica de negocio\")\n"
        "        ContainerDb(bd, \"Base de Datos\", \"PostgreSQL\", \"Almacena datos de cuentas\")\n"
        "    }\n"
        "    Rel(cliente, appWeb, \"Usa\", \"HTTPS\")\n"
        "    Rel(appWeb, api, \"Consume\", \"JSON/HTTPS\")\n"
        "    Rel(api, bd, \"Lee/Escribe\", \"SQL\")\n"
        "    Rel(api, sistemaCorreo, \"Envía notificaciones\", \"SMTP\")\n"
        "    UpdateLayoutConfig($c4ShapeInRow=\"2\", $c4BoundaryInRow=\"1\")"
    ),

    "Diagrama de Despliegue C4": lambda texto: (
        "Eres un experto en arquitectura de software e infraestructura. Tu tarea es generar un diagrama C4 de DESPLIEGUE (Nivel 4).\n\n"
        "PROPÓSITO: Mostrar cómo se despliegan los contenedores en la infraestructura física/virtual (servidores, máquinas virtuales, containers, bases de datos).\n\n"
        "- Comienza el código con:\n"
        "  C4Deployment\n\n"
        "- Trata de sea en español las especificaciones y descripciones"
        "- Los diagramas deben tener un orden entendible"
        "Estructura y elementos obligatorios:\n"
        "- Usa Deployment_Node(alias, nombre, tipo, descripción) para representar nodos físicos o virtuales.\n"
        "- También puedes usar:\n"
        "  - Node(): versión corta de Deployment_Node()\n"
        "  - Node_L(): alineado a la izquierda\n"
        "  - Node_R(): alineado a la derecha\n"
        "- Dentro de los nodos se colocan:\n"
        "  - Container(alias, nombre, tecnología, descripción) para aplicaciones.\n"
        "  - ContainerDb(alias, nombre, tecnología, descripción) para bases de datos.\n"

        "Relaciones:\n"
        "- Usa Rel(origen, destino, descripción, protocolo) para relaciones unidireccionales.\n"
        "- Usa Rel_U(), Rel_D(), Rel_L(), Rel_R() si quieres controlar la dirección de la flecha.\n"

        "Estilos personalizados:\n"
        "- Usa UpdateRelStyle(origen, destino, $textColor=\"\", $lineColor=\"\", $offsetX=\"\", $offsetY=\"\") para personalizar relaciones.\n"
        "- Usa UpdateLayoutConfig($c4ShapeInRow=\"\", $c4BoundaryInRow=\"\") para controlar la distribución visual.\n\n"

        "Devuelve solo el código Mermaid. No uses la palabra 'mermaid', comillas ni backticks.\n\n"

        "Ejemplo:\n"

        "C4Deployment\n"
        "    title Deployment Diagram for Internet Banking System - Live\n\n"
        "    Deployment_Node(mob, \"Customer's mobile device\", \"Apple IOS or Android\") {\n"
        "        Container(mobile, \"Mobile App\", \"Xamarin\", \"Provides a limited subset of the Internet Banking functionality to customers via their mobile device.\")\n"
        "    }\n\n"
        "    Deployment_Node(comp, \"Customer's computer\", \"Microsoft Windows or Apple macOS\") {\n"
        "        Deployment_Node(browser, \"Web Browser\", \"Google Chrome, Mozilla Firefox,<br/> Apple Safari or Microsoft Edge\") {\n"
        "            Container(spa, \"Single Page Application\", \"JavaScript and Angular\", \"Provides all of the Internet Banking functionality to customers via their web browser.\")\n"
        "        }\n"
        "    }\n\n"
        "    Deployment_Node(plc, \"Big Bank plc\", \"Big Bank plc data center\") {\n"
        "        Deployment_Node(dn, \"bigbank-api*** x8\", \"Ubuntu 16.04 LTS\") {\n"
        "            Deployment_Node(apache, \"Apache Tomcat\", \"Apache Tomcat 8.x\") {\n"
        "                Container(api, \"API Application\", \"Java and Spring MVC\", \"Provides Internet Banking functionality via a JSON/HTTPS API.\")\n"
        "            }\n"
        "        }\n"
        "        Deployment_Node(bb2, \"bigbank-web*** x4\", \"Ubuntu 16.04 LTS\") {\n"
        "            Deployment_Node(apache2, \"Apache Tomcat\", \"Apache Tomcat 8.x\") {\n"
        "                Container(web, \"Web Application\", \"Java and Spring MVC\", \"Delivers the static content and the Internet Banking single page application.\")\n"
        "            }\n"
        "        }\n"
        "        Deployment_Node(bigbankdb01, \"bigbank-db01\", \"Ubuntu 16.04 LTS\") {\n"
        "            Deployment_Node(oracle, \"Oracle - Primary\", \"Oracle 12c\") {\n"
        "                ContainerDb(db, \"Database\", \"Relational Database Schema\", \"Stores user registration information, hashed authentication credentials, access logs, etc.\")\n"
        "            }\n"
        "        }\n"
        "        Deployment_Node(bigbankdb02, \"bigbank-db02\", \"Ubuntu 16.04 LTS\") {\n"
        "            Deployment_Node(oracle2, \"Oracle - Secondary\", \"Oracle 12c\") {\n"
        "                ContainerDb(db2, \"Database\", \"Relational Database Schema\", \"Stores user registration information, hashed authentication credentials, access logs, etc.\")\n"
        "            }\n"
        "        }\n"
        "    }\n\n"
        "    Rel(mobile, api, \"Makes API calls to\", \"json/HTTPS\")\n"
        "    Rel(spa, api, \"Makes API calls to\", \"json/HTTPS\")\n"
        "    Rel_U(web, spa, \"Delivers to the customer's web browser\")\n"
        "    Rel(api, db, \"Reads from and writes to\", \"JDBC\")\n"
        "    Rel(api, db2, \"Reads from and writes to\", \"JDBC\")\n"
        "    Rel_R(db, db2, \"Replicates data to\")\n\n"
        "    UpdateRelStyle(spa, api, $offsetY=\"-40\")\n"
        "    UpdateRelStyle(web, spa, $offsetY=\"-40\")\n"
        "    UpdateRelStyle(api, db, $offsetY=\"-20\", $offsetX=\"5\")\n"
        "    UpdateRelStyle(api, db2, $offsetX=\"-40\", $offsetY=\"-20\")\n"
        "    UpdateRelStyle(db, db2, $offsetY=\"-10\")"
    ),

    "Diagrama de Componente C4": lambda diagramas_secuencia, diagrama_er: (
        "Eres un experto en arquitectura de software y diagramas C4. Tu tarea es generar un diagrama C4 de COMPONENTE (Nivel 3).\n\n"
        "PROPÓSITO: Mostrar la descomposición interna de un contenedor en sus componentes/módulos (controladores, servicios, repositorios).\n\n"
        "CONTEXTO DE APOYO:\n"
        "Este diagrama se basa en:\n"
        "- Diagrama de Secuencia: Define cómo interactúan los componentes entre ellos\n"
        "- Diagrama de Entidad-Relación (ERD): Define la estructura de datos que manejan los componentes\n\n"
        f"DIAGRAMAS DE SECUENCIA (Define interacciones entre componentes):\n{diagramas_secuencia}\n\n"
        f"DIAGRAMA DE ENTIDAD-RELACIÓN (Define estructura de datos):\n{diagrama_er}\n\n"
        "INSTRUCCIONES PARA GENERAR EL DIAGRAMA:\n\n"
        "1. Define el CONTENEDOR que estás descomponiendo:\n"
        "   - Típicamente es el Backend/API\n"
        "   - Usa Container_Boundary(alias, nombre) para delimitar\n\n"
        "2. Identifica los COMPONENTES principales:\n"
        "   - Usa Component(alias, nombre, tecnología, descripción) para componentes de lógica\n"
        "   - Usa ComponentDb(alias, nombre, tecnología, descripción) para repositorios/DAOs\n"
        "   - Ejemplos: Controllers, Services, Repositories, Utils\n\n"
        "3. Muestra las DEPENDENCIAS entre componentes:\n"
        "   - Usa Rel(origen, destino, descripción) para relaciones\n"
        "   - Los controladores llaman a servicios\n"
        "   - Los servicios usan repositorios\n"
        "   - Los repositorios acceden a la base de datos\n\n"
        "4. INCLUYE actores externos relevantes:\n"
        "   - Usa Person(alias, nombre, descripción) para usuarios del contenedor\n"
        "   - Usa System_Ext(alias, nombre, descripción) para sistemas externos\n\n"
        "5. Hazlo en español según corresponda\n"
        "6. Enfócate en responsabilidades y flujos de datos\n\n"
        "SINTAXIS MERMAID:\n"
        "- Comienza SIEMPRE con: C4Component\n"
        "- Devuelve SOLO el código Mermaid, sin comillas ni backticks\n"
        "- No incluyas la palabra 'mermaid'\n\n"
        "EJEMPLO BÁSICO:\n"
        "C4Component\n"
        "    title Diagrama de Componente - Backend de Banca\n"
        "    Person(cliente, \"Cliente\", \"Usuario del sistema bancario\")\n"
        "    System_Ext(sistemaCorreo, \"Sistema de Correo\", \"Envía notificaciones\")\n"
        "    Container_Boundary(backend, \"Backend API\") {\n"
        "        Component(controlador, \"Controlador de Cuentas\", \"Spring Controller\", \"Recibe solicitudes HTTP\")\n"
        "        Component(servicio, \"Servicio de Cuentas\", \"Spring Service\", \"Lógica de negocio\")\n"
        "        Component(repositorio, \"Repositorio de Cuentas\", \"Spring Data JPA\", \"Acceso a datos\")\n"
        "        ComponentDb(baseDatos, \"Base de Datos\", \"PostgreSQL\", \"Almacena información\")\n"
        "    }\n"
        "    Rel(cliente, controlador, \"Realiza solicitudes\", \"HTTP\")\n"
        "    Rel(controlador, servicio, \"Llama\", \"Java\")\n"
        "    Rel(servicio, repositorio, \"Usa\", \"Java\")\n"
        "    Rel(repositorio, baseDatos, \"Lee/Escribe\", \"SQL\")\n"
        "    Rel(servicio, sistemaCorreo, \"Notifica\", \"SMTP\")\n"
        "    UpdateLayoutConfig($c4ShapeInRow=\"2\", $c4BoundaryInRow=\"1\")"
    ),

    "caja_negra": lambda requisito_funcional, diagrama_flujo=None, historia_usuario=None: (
    "Eres un ingeniero de software experto en aseguramiento de calidad (QA) especializado "
    "en pruebas funcionales de caja negra.\n\n"
    "Tu tarea es generar ÚNICAMENTE las siguientes secciones de una prueba de caja negra: "
    "OBJETIVO, DATOS DE ENTRADA y PROCEDIMIENTO / PASOS.\n"
    "Analiza el verbo principal del requisito funcional para formular el objetivo, "
    "deduce los posibles datos de entrada y describe pasos lógicos y claros para validar el requisito.\n\n"
    f"REQUISITO FUNCIONAL:\n{requisito_funcional}\n\n" +
    (f"DIAGRAMA DE FLUJO (si existe):\n{diagrama_flujo}\n\n" if diagrama_flujo else "") +
    (f"HISTORIA DE USUARIO (si existe):\n{historia_usuario}\n\n" if historia_usuario else "") +
    "Genera la salida con el siguiente formato EXACTO (sin explicaciones ni texto adicional):\n\n"
    "OBJETIVO:\n"
    "[Validar que el sistema ...]\n\n"
    "DATOS DE ENTRADA:\n"
    "[Lista de datos de entrada separados por comas]\n\n"
    "PROCEDIMIENTO / PASOS:\n"
    "1. [Paso 1]\n"
    "2. [Paso 2]\n"
    "3. [Paso 3]\n"
    "4. [Paso 4]\n"
    "5. [Paso 5]\n\n"
    "RESULTADO ESPERADO:\n"
    "El sistema debe [acción esperada principal del RF], mostrando [salida o confirmación esperada], "
    "y registrando [efecto o cambio en el sistema] según lo indicado en los pasos anteriores.\n"
    ),

}

# ===== FUNCIONES DE GENERACIÓN =====

def _generar_contenido(prompt: str) -> str:
    try:
        model = genai.GenerativeModel(MODEL) # pyright: ignore[reportPrivateImportUsage]
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        return f"[ERROR] No se pudo generar contenido: {e}"

def generar_subartefacto_con_prompt(tipo: str, **kwargs) -> str:
    if tipo not in PROMPTS:
        raise ValueError (f"[ERROR] Tipo de artefacto desconocido: {tipo}")

    prompt_func = PROMPTS[tipo]
    prompt = prompt_func(**kwargs)
    return _generar_contenido(prompt)

#=====  codigo de extrae reqquisitos de la HU=======
def extraer_requisitos(historia_texto: str) -> str:
    prompt = (
        "Eres un ingeniero de software especializado en análisis de requisitos.\n"
        "Dada la siguiente lista de historias de usuario, cada una identificada con HU y su número secuencial:\n"
        f"{historia_texto}\n"
        "Extrae exactamente los requisitos funcionales clave para cada historia de usuario. "
        "Enumera cada requisito como RF (Requisito Funcional) seguido del número secuencial correspondiente (por ejemplo, RF1, RF2, etc.).\n"
        "Cada requisito debe ser claro, específico y estar redactado en tercera persona.\n"
        "Devuelve únicamente la lista de requisitos, uno por línea, sin títulos, numeración adicional ni explicaciones."
    )
    return _generar_contenido(prompt)

